/**
 * Task 3 normalization of the 75-item `seedCatalog` array from
 * .claude/index.html (the localStorage prototype) into CatalogItem rows.
 *
 * Every field beyond sourceId/name/description/price/cost/taxable/active is
 * an inference — unitOfMeasure, calcType, and wattage aren't present in the
 * source data and were derived from the item's name/description text. Where
 * that inference wasn't confident, needsReview is true and reviewNotes
 * explains why, rather than silently guessing. isSuspectedDuplicate marks
 * near-identical entries that were deliberately kept as separate rows, not
 * merged — see reviewNotes on each flagged pair.
 *
 * This file is the single source of truth for both seed paths: the Prisma
 * seed script (prisma/seed.ts) and the in-memory repo fallback consume the
 * exact same array, so catalog data is identical with or without a database.
 */

export type UnitOfMeasure = "EACH" | "LINEAR_FT" | "HOUR" | "JOB";

export type CalcType =
  | "UPLIGHT"
  | "PATH"
  | "WELL"
  | "WALL_WASH"
  | "ACCENT"
  | "UNDERWATER"
  | "DECK"
  | "TRANSFORMER"
  | "WIRE"
  | "TIMER"
  | "HOLIDAY"
  | "SERVICE"
  | "LABOR"
  | "MATERIAL"
  | "OTHER";

export interface CatalogItemSeed {
  sourceId: number;
  name: string;
  description: string | null;
  unitOfMeasure: UnitOfMeasure;
  calcType: CalcType;
  wattage: number | null;
  price: number;
  cost: number;
  taxable: boolean;
  active: boolean;
  isPlaceholder: boolean;
  isSuspectedDuplicate: boolean;
  needsReview: boolean;
  reviewNotes: string | null;
}

const DUP_3_64 =
  "Same PAR36 / 15W / 1500-lumen / 60° beam / 5-yr-warranty spec as the other item in this pair, listed under a different fixture type (Well vs Spot). Kept as separate rows per instruction — confirm whether this is one physical bulb sold under two catalog entries or two distinct SKUs.";

const DUP_6_7 =
  "Suspected duplicate of the other 'WAC Colorscaping Grand Accent 24 Watt' entry — nearly identical name ('24 Watt' vs '24 - Watt'), identical price, different description text. Kept as separate rows per instruction — confirm which is authoritative or if both are intentional.";

const DUP_49_63 =
  "Same fixture spec (180° beam spread, directional L-shaped pathway light, 6.5W) as the other item in this pair, at a different price/cost and without the WAC/Balance/3000k branding. Kept as separate rows per instruction — confirm whether these are the same physical fixture listed twice or genuinely different SKUs.";

const BULLET_NOTE =
  "'Bullet' fixtures are conventionally uplights in landscape lighting trade parlance, but no UPLIGHT keyword appears in the name/description — mapped by convention, not stated. Confirm.";

const SPOT_NOTE =
  "'Spot Light' has no dedicated calcType in the schema — mapped to ACCENT as the closest fit. This is a judgment call, not a textual match.";

const TIMER_BUNDLE_NOTE =
  "Bundles a transformer and a digital timer into one SKU — modeled as a single TRANSFORMER item for now; the timer isn't separately represented. Confirm whether this should decompose into two line items via an Option in Task 6.";

export const normalizedCatalogSeed: CatalogItemSeed[] = [
  {
    sourceId: 1,
    name: "Materials",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Generic catch-all line item with no description — unit and real use are unclear. Confirm how this is used in practice or retire it.",
  },
  {
    sourceId: 2,
    name: "WAC Tiki Pathway 6.5 Watt",
    description: "15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: 6.5,
    price: 299,
    cost: 131.17,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 3,
    name: "Par 36 Well Light 15 Watt",
    description: "60 Deg Beam\n1500 Lumen \n5 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: 15,
    price: 368.34,
    cost: 97.68,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: DUP_3_64,
  },
  {
    sourceId: 4,
    name: 'Brass Riser 6"',
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 16,
    cost: 12.01,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 5,
    name: "Lumien Micro Recessed Flush Mount 3.5 Watt 3000K Square Lid",
    description: "10 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "DECK",
    wattage: 3.5,
    price: 215,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "'Recessed Flush Mount' doesn't map cleanly to an existing calcType — guessed DECK (flush-mount deck/step light); could also be a hardscape/step light under a different category. Confirm.",
  },
  {
    sourceId: 6,
    name: "WAC Colorscaping Grand Accent 24 Watt Adjustable Beam Spread",
    description: "1+ Million Colors plus whites 2700K-6500K Fully Programable",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: 24,
    price: 550,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: DUP_6_7,
  },
  {
    sourceId: 7,
    name: "WAC Colorscaping Grand Accent 24 - Watt Adjustable Beam Spread",
    description:
      "1 Million Colors Fully Programable + 2700k-6500K Whites, 15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: 24,
    price: 550,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: DUP_6_7,
  },
  {
    sourceId: 8,
    name: "WAC Colorscaping 300 Watt Transformer",
    description: "15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "TRANSFORMER",
    wattage: 300,
    price: 699,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 9,
    name: "WAC Grand Well Light Adjustable Beam Spread Adjustable Wattage 2-25 Watt 3000k Color",
    description: "15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: null,
    price: 550,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "Wattage is adjustable across a 2-25W range, not a single value — left null rather than guessing a midpoint.",
  },
  {
    sourceId: 10,
    name: "WAC Grand Accent Fully Adjustable 15-33 Watts 2000 Lumen 3000K Color",
    description: "15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: null,
    price: 399,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "Wattage is adjustable across a 15-33W range — left null rather than guessing.",
  },
  {
    sourceId: 11,
    name: "WAC L Shaped Pathway Light 6 Watt 3000k Color",
    description: "15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: 6,
    price: 275,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 12,
    name: "Brass Underwater Lights 7 Watt 700 Lumen 3000k Color",
    description: "Lifetime Warranty",
    unitOfMeasure: "EACH",
    calcType: "UNDERWATER",
    wattage: 7,
    price: 249,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 13,
    name: "WAC Deck Light Bronze 3 Watts",
    description: "15 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "DECK",
    wattage: 3,
    price: 249,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 14,
    name: "WAC Colorscaping Accent Fully Adjustable, Fully Programable Spot Light Adjustable Beam Spread",
    description:
      "1+ Million Colors plus 2700k-6500k White, Individually Controlled, Groups, Zones, Scenes, Holidays 15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: null,
    price: 450,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: `${SPOT_NOTE} No wattage stated in name/description.`,
  },
  {
    sourceId: 15,
    name: "WAC Colorscaping Accent Fully Adjustable, Fully Programable Well Light Adjustable Beam Spread",
    description:
      "1+ Million Colors plus 2700k-6500k White, Individually Controlled, Groups, Zones, Scenes, Holidays 15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: null,
    price: 599,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 16,
    name: "WAC Colorscaping Grand Accent Fully Adjustable, Fully Programable Adjustable Beam Spread",
    description:
      "1+ Million Colors plus 2700k-6500k White, Individually Controlled, Groups, Zones, Scenes, Holidays 15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: null,
    price: 550,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 17,
    name: "WAC Colorscaping Balance Pathway Fully Programable",
    description:
      "1+ Million Colors plus 2700k-6500k White, Individually Controlled, Groups, Zones, Scenes, Holidays 15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: null,
    price: 349,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 18,
    name: "WAC Colorscaping Wall Wash Fully Adjustable, Fully Programable Adjustable Beam Spread",
    description:
      "1+ Million Colors plus 2700k-6500k White, Individually Controlled, Groups, Zones, Scenes, Holidays 15 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: null,
    price: 550,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 19,
    name: "Service Call",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "SERVICE",
    wattage: null,
    price: 0,
    cost: 125,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 20,
    name: 'Adjustable Riser 12-24"',
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 35,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 21,
    name: "DT200LT Digital Timer",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "TIMER",
    wattage: null,
    price: 55,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 22,
    name: "Service and Maintenance",
    description:
      "- Remove calcium from lenses\n- Trim vegetation as needed\n- Inspect voltage and timers\n- Reposition and secure fixtures as necessary",
    unitOfMeasure: "JOB",
    calcType: "SERVICE",
    wattage: null,
    price: 160,
    cost: 0,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 23,
    name: "Bulb Replacment",
    description: "Replacement of broken bulbs",
    unitOfMeasure: "EACH",
    calcType: "SERVICE",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Could be SERVICE (labor only) or MATERIAL (bulb + labor bundled) — $0 price suggests it's billed via the actual bulb line item elsewhere. Confirm intended structure.",
  },
  {
    sourceId: 24,
    name: "Fixture Shipping",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "OTHER",
    wattage: null,
    price: 25,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 25,
    name: "Digital Timer",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "TIMER",
    wattage: null,
    price: 38,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 26,
    name: "Fixture Cleaning",
    description: "Fixtures scrubbed with solution to remove lime/buildup on fixtures",
    unitOfMeasure: "EACH",
    calcType: "SERVICE",
    wattage: null,
    price: 65,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Unit guessed as EACH (per fixture) but could be billed per visit (JOB) covering multiple fixtures — confirm billing model.",
  },
  {
    sourceId: 27,
    name: "Holiday String Light Wrap",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "HOLIDAY",
    wattage: null,
    price: 1720.76,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Flat price suggests a per-job (whole-property) charge rather than per-fixture or per-linear-foot — confirm unit.",
  },
  {
    sourceId: 28,
    name: "Palm Tree Wrapping",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "HOLIDAY",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "$0 price suggests this varies by tree height/size and is quoted per tree at estimate time — confirm whether a size-tiered SKU structure (like 'Large Tree Wrapping', id 57) should exist instead of one $0 catch-all.",
  },
  {
    sourceId: 29,
    name: "Replacement Bulb",
    description: "7 watt\n630 lumen",
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: 7,
    price: 25,
    cost: 15.13,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 30,
    name: "Service and Repair",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "SERVICE",
    wattage: null,
    price: 125,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 31,
    name: "Services",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "SERVICE",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Name is fully generic ('Services') — cannot confidently infer what this line item actually represents. Confirm intended use or retire.",
  },
  {
    sourceId: 32,
    name: "Sconces and Electrical work",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "SERVICE",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Name conflates a fixture (sconce) with labor ('Electrical work') — unclear whether this should be a MATERIAL (fixture), a SERVICE (labor), or split into two line items. $0 price confirms it isn't fully defined yet.",
  },
  {
    sourceId: 33,
    name: "Surface Mount",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 12,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Could be a physical mounting hardware accessory (MATERIAL) or a labor adder for surface- vs recessed-mount installs (SERVICE/LABOR) — low price is consistent with either. Confirm.",
  },
  {
    sourceId: 34,
    name: "Remote",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 50,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 35,
    name: "WAC Linear Path Light",
    description: "15 year warranty",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: null,
    price: 269,
    cost: 107.1,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 36,
    name: "WAC Grand Wall Wash",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: null,
    price: 438,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 37,
    name: "Credit Card Processing Fee",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "OTHER",
    wattage: null,
    price: 0,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: true,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "This is a percentage-based processing fee, not a fixture/service with a natural per-unit quantity — the EACH unit is a placeholder only. Confirm how this should actually be modeled (e.g. computed from the quote total rather than a line item at all).",
  },
  {
    sourceId: 38,
    name: "WAC Accent 18 Watt 1190 Lumen",
    description: "Adjustable Beam Spread and Wattage 1-18 Watt",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: 18,
    price: 329,
    cost: 123.34,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 39,
    name: "In Ground Well Light w/ 7 Watt Bulb",
    description: "60 Deg Beam\n630 Lumen \n5 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: 7,
    price: 233.18,
    cost: 65.16,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 40,
    name: "WAC Hornet Brass Bullet 10.5 Watts 820 Lumen",
    description: "Built in Adjustable Beam Spread 20-70 degree\n15 year warranty",
    unitOfMeasure: "EACH",
    calcType: "UPLIGHT",
    wattage: 10.5,
    price: 256.8,
    cost: 85.6,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: BULLET_NOTE,
  },
  {
    sourceId: 41,
    name: "WAC Wall Wash 18 Watt 1000 Lumen",
    description: "Adjustable Wattage 1-18 Watts \n50x80 Degree Beam Angle",
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: 18,
    price: 339,
    cost: 150.42,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 42,
    name: "900 Watt Transformer w/ Digital Timer",
    description: "12-22 volt \nLifetime Warranty",
    unitOfMeasure: "EACH",
    calcType: "TRANSFORMER",
    wattage: 900,
    price: 949.99,
    cost: 569,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: TIMER_BUNDLE_NOTE,
  },
  {
    sourceId: 43,
    name: "Brass Riser 1ft",
    description:
      "Risers are utilized to elevate fixtures above shrubs or obstacles, effectively directing light towards the intended subject",
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 29,
    cost: 23.01,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 44,
    name: "Brass Riser 2ft",
    description:
      "Risers are utilized to elevate fixtures above shrubs or obstacles, effectively directing light towards the intended subject",
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 54,
    cost: 45.61,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 45,
    name: "600 Watt Transformer w/ Digital Timer (High Tap)",
    description: "12-22 volt \nLifetime Warranty",
    unitOfMeasure: "EACH",
    calcType: "TRANSFORMER",
    wattage: 600,
    price: 499,
    cost: 235.38,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: TIMER_BUNDLE_NOTE,
  },
  {
    sourceId: 46,
    name: "WAC Power Accent Colorscaping",
    description: "1+ Million Colors plus whites 2700K-6500K Fully\nProgramable\n14 watt\n1125 lumen",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: 14,
    price: 599,
    cost: 282.79,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 47,
    name: "RGBW Remote",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "MATERIAL",
    wattage: null,
    price: 100,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 48,
    name: "WAC Colorscaping Wall Sconce",
    description: "Up and down lighting",
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: null,
    price: 399,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "'Wall Sconce' (a fixed architectural fixture) doesn't map cleanly to any existing calcType — guessed WALL_WASH as the closest fit given the 'up and down lighting' description, but this is a distinct fixture style. No wattage stated. Confirm.",
  },
  {
    sourceId: 49,
    name: "WAC Balance L-Shaped Pathway 6.5 Watt 3000k",
    description: "180 degree beam spread\nDirectional pathway lighting",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: 6.5,
    price: 299,
    cost: 135.98,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: DUP_49_63,
  },
  {
    sourceId: 50,
    name: "Brass Bullet 7 watt 700 Lumen",
    description: "Built in Adjustable Beam Spread 50,000 Hour Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "UPLIGHT",
    wattage: 7,
    price: 209,
    cost: 65,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: BULLET_NOTE,
  },
  {
    sourceId: 51,
    name: "Lumien Micro Well 5.5 Watt 60 Deg",
    description: "10 Year Warranty on Entire Fixture",
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: 5.5,
    price: 209,
    cost: 70,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 52,
    name: "Dauer Icon Brass Bullet w/ 7 Watt Bulb",
    description: "60 Deg Beam\n630 Lumen \n5 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "UPLIGHT",
    wattage: 7,
    price: 224.43,
    cost: 53.65,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: BULLET_NOTE,
  },
  {
    sourceId: 53,
    name: "Dauer Omni Architectural Lighting",
    description:
      "Price per Linear Ft\n\n-Mobile App Control\n-Individually Addressable Lights\n-RGBW with Unlimited Color Options \n-8\" Spacing\n-Controllable Scenes\n-Dimmable\n\n5 Year Warranty",
    unitOfMeasure: "LINEAR_FT",
    calcType: "OTHER",
    wattage: null,
    price: 45,
    cost: 15,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Addressable RGBW linear architectural strip lighting — no existing calcType fits an addressable linear-foot system. Wattage varies by run length, not stated. Confirm calcType or whether a new category is needed. Unit (LINEAR_FT) is explicit in the description ('Price per Linear Ft') and confident.",
  },
  {
    sourceId: 54,
    name: "10-2 Landscape Wire",
    description: null,
    unitOfMeasure: "LINEAR_FT",
    calcType: "WIRE",
    wattage: null,
    price: 1.25,
    cost: 0.72,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 55,
    name: "Soffit Lighting",
    description:
      "Slim, weather-resistant LED fixtures mounted in soffits to provide clean, even illumination along the home’s exterior. Designed for durability, low maintenance, and a high-end architectural look",
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: null,
    price: 299,
    cost: 0,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Soffit-mounted linear LED washing down a home's exterior — guessed WALL_WASH for the wash effect, but this may really be its own category or priced per linear foot of soffit run rather than a flat EACH price. No wattage stated. Confirm.",
  },
  {
    sourceId: 56,
    name: "Roofline Lighting (C9 LED, warm white)",
    description:
      "Professional-grade C9 LED bulbs custom cut to fit your roofline for a clean, tailored appearance. Installed with commercial-grade wire and clips to ensure all bulbs are perfectly straight and secure. Energy-efficient LEDs use minimal power and produce a warm, classic holiday glow. Installation includes all materials, professional setup, and removal at the end of the season.",
    unitOfMeasure: "LINEAR_FT",
    calcType: "HOLIDAY",
    wattage: null,
    price: 12,
    cost: 1.75,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Unit inferred as LINEAR_FT from 'custom cut to fit your roofline' and the low per-unit price — not explicitly stated as a per-foot price in the description. Confirm.",
  },
  {
    sourceId: 57,
    name: "Large Tree Wrapping (18+ Ft)",
    description:
      "Installation of commercial-grade red and green 5 mm LED mini lights wrapped tightly around the trunk and primary limbs of a large oak or similar feature tree (up to approx. 20 ft tall). All lights are professionally installed with hidden leads, clean color transitions, and waterproof connections. Includes take-down and storage prep after the season.",
    unitOfMeasure: "EACH",
    calcType: "HOLIDAY",
    wattage: null,
    price: 850,
    cost: 200,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 58,
    name: "Outdoor Lighting Timer (Programmable)",
    description:
      "Heavy-duty outdoor-rated digital timer to automate your holiday lighting schedule. Pre-programmed at installation for daily on/off cycles to maximize efficiency and reduce energy costs. Client may adjust settings as desired.",
    unitOfMeasure: "EACH",
    calcType: "TIMER",
    wattage: null,
    price: 15.99,
    cost: 15.99,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 59,
    name: "Smart Timer",
    description: "*Requires Strong Wifi",
    unitOfMeasure: "EACH",
    calcType: "TIMER",
    wattage: null,
    price: 109.99,
    cost: 37.69,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 60,
    name: "Driveway Cut + Fill",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "OTHER",
    wattage: null,
    price: 125,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Unit guessed as JOB (per driveway crossing) — no length given to consider LINEAR_FT instead. Confirm.",
  },
  {
    sourceId: 61,
    name: "1200 Watt Transformer w/ Digital Timer",
    description: "12-22 volt \nLifetime Warranty",
    unitOfMeasure: "EACH",
    calcType: "TRANSFORMER",
    wattage: 1200,
    price: 1149,
    cost: 610,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: TIMER_BUNDLE_NOTE,
  },
  {
    sourceId: 62,
    name: "Round Top Pathway Light",
    description: "360 deg pathway lighting\n5 year warranty",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: null,
    price: 267.4,
    cost: 70,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 63,
    name: "L-Shaped Pathway 6.5 Watt",
    description: "180 degree beam spread\nDirectional pathway lighting",
    unitOfMeasure: "EACH",
    calcType: "PATH",
    wattage: 6.5,
    price: 259,
    cost: 95,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: DUP_49_63,
  },
  {
    sourceId: 64,
    name: "Par 36 Spot Light 15 Watt Bulb",
    description: "60 Deg Beam\n1500 Lumen \n5 Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: 15,
    price: 348.74,
    cost: 120.86,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: true,
    needsReview: true,
    reviewNotes: `${DUP_3_64} ${SPOT_NOTE}`,
  },
  {
    sourceId: 65,
    name: "WAC Mini Wall Wash 8 Watt 420 Lumen",
    description: "15 year warranty",
    unitOfMeasure: "EACH",
    calcType: "WALL_WASH",
    wattage: 8,
    price: 273.64,
    cost: 125.13,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 66,
    name: "10-2 Wire Spool",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "WIRE",
    wattage: null,
    price: 463.54,
    cost: 358.79,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 67,
    name: "200 Watt Transformer w/ Digital Timer",
    description: "12-15 volt\nLifetime warranty",
    unitOfMeasure: "EACH",
    calcType: "TRANSFORMER",
    wattage: 200,
    price: 329,
    cost: 192.58,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: TIMER_BUNDLE_NOTE,
  },
  {
    sourceId: 68,
    name: "WAC In Ground Well Light",
    description: null,
    unitOfMeasure: "EACH",
    calcType: "WELL",
    wattage: null,
    price: 316.92,
    cost: 0,
    taxable: false,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: "No wattage stated in name/description.",
  },
  {
    sourceId: 69,
    name: "Brilliance Mini Beam w/ Shroud",
    description: "Installed on arches-\n\n\n400 Lumen \n7 year warranty",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: null,
    price: 204.63,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "'Mini Beam' has no dedicated calcType — mapped to ACCENT as the closest fit. Only lumens (400) are given, no wattage.",
  },
  {
    sourceId: 70,
    name: "Line Voltage Fixture Removal",
    description:
      "Removal of existing line voltage landscape lighting in areas where low voltage will be installed",
    unitOfMeasure: "JOB",
    calcType: "SERVICE",
    wattage: null,
    price: 4200,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
  {
    sourceId: 71,
    name: "Labor",
    description: null,
    unitOfMeasure: "HOUR",
    calcType: "LABOR",
    wattage: null,
    price: 350,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Unit guessed as HOUR (labor is conventionally billed hourly), but the flat $350 price could represent a fixed labor block instead — confirm rate structure.",
  },
  {
    sourceId: 72,
    name: "Brass Bullet RGB-WW (Bluetooth/Wifi Control)",
    description:
      "*Front Yard Fixtures*\n\nMaterial: Brass\n\nSmart RGB-WW Bluetooth bullet shroud light\n\nLamp Type: Integrated LED\n1-6W RGB LED module. Lumen output is between 15LM - 450LM",
    unitOfMeasure: "EACH",
    calcType: "UPLIGHT",
    wattage: null,
    price: 318.47,
    cost: 155.5031,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: `${BULLET_NOTE} Wattage is an adjustable 1-6W RGB LED module range, not a single value — left null.`,
  },
  {
    sourceId: 73,
    name: "Brass Remote Controlled Color Spot 650 Lumen",
    description:
      "Material: Brass\n\nRemote Controlled\n\nLight Output (White - 2700K): 650 Lumens (brightest), 100 Lumens (dimmest)\nRed: 215 Lumens | Green: 420 Lumens | Blue: 100 Lumens (Max Outputs)",
    unitOfMeasure: "EACH",
    calcType: "ACCENT",
    wattage: null,
    price: 268.28,
    cost: 115,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes: `${SPOT_NOTE} Only lumens are given, no wattage.`,
  },
  {
    sourceId: 74,
    name: "Mantis Dock Light Kit 3-Lights",
    description:
      "Full RGBW Color Changing (Spectrum)\nAdd-on light available (4 lights max per kit)\nPlugs into any standard switched outlet\nComplete kit includes everything needed for easy installation on most pilling or seawalls\n2,000 Lumens output per light\nMade in USA\nUL Listed\n5-Year Warranty",
    unitOfMeasure: "EACH",
    calcType: "OTHER",
    wattage: null,
    price: 1969.97,
    cost: 1969.97,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: true,
    reviewNotes:
      "Dock/marine lighting doesn't map to any existing calcType — no close fit among uplight/path/well/wall-wash/underwater/deck. Also a 3-light kit sold as one SKU — confirm whether it should decompose into 3 individual line items instead. Note: cost equals price (0% margin) — worth confirming that's intentional and not a placeholder cost.",
  },
  {
    sourceId: 75,
    name: "Fisher Island Clearance Fees",
    description: null,
    unitOfMeasure: "JOB",
    calcType: "OTHER",
    wattage: null,
    price: 504.51,
    cost: 0,
    taxable: true,
    active: true,
    isPlaceholder: false,
    isSuspectedDuplicate: false,
    needsReview: false,
    reviewNotes: null,
  },
];
